### ISSUE TITLE
Support suite for @UserDefault

### ISSUE THREAD

**Issue by AlbGarciam** [alexruperez/SecurePropertyStorage#12]
**Is your feature request related to a problem? Please describe.**
I want to be able to share user defaults data between bundles inside the same app group (i.e App and Widget)

**Describe the solution you'd like**
The best could be to have an additional field in @UserDefault property wrapper to specify the app name and if not provided, use the standard value

**Comment by alexruperez** [comment]
Hi @AlbGarciam, you can create a [@Store(...)](https://github.com/alexruperez/SecurePropertyStorage/blob/master/Sources/Storage/Store.swift#L40) by passing it a [UserDefaultsStorage](https://github.com/alexruperez/SecurePropertyStorage/blob/master/Sources/UserDefault/UserDefaultsStorage.swift#L33) with your suiteName. Does that fit?

**Comment by AlbGarciam** [comment]
Yes, this could fit, Thanks!
