### ISSUE TITLE
Nonce reuse is bad

### ISSUE THREAD

**Issue by shphilippe** [alexruperez/SecurePropertyStorage#13]
For some unknown reason this library is using a fixed nonce. This is bad as AES-GCM can be trivially broken if a nonce is ever reused with the same key ( https://www.elttam.com/blog/key-recovery-attacks-on-gcm/ ).

I suggest the following: Remove all the nonce generation and saving logic in the keychain and all the custom nonce management code. AES.GCM.seal() will generate a random nonce if none is provided. The nonce does not need to be saved/generated/handled: AES.GCM.seal will serialize the nonce with the cyphertext in the combined representation and automatically read it back in constructor :  AES.GCM.SealedBox(combined: data). It is totally transparant to the user ot the AES.GCM api.

Note: a key can be reused securely up to a certain extent with AES-GCM (IIRC 64Gb max per key), thus to have a really secure storage, a key rotation should be implemented.

**Comment by alexruperez** [comment]
Thanks @shphilippe, let me know if #14 fix the issue and please, if you have some time, propose a symmetric key rotation implementation without losing stored data.

**Comment by shphilippe** [comment]
@alexruperez I checked the PR, the code fix is good to fix future usage of the library
There is no easy way to fix existing implementation. And since keychain items are persistant even across app uninstall & reinstall, all current users should assume that the properties are compromised even after an update. If you want to fix current user, one solution I see is to create a new key with a new name in the keychain and convert all properties on load from the old key to the new one. In order to know if the property has already been converted there is two solution:
- Hack: try to decrypt, see if you can (aes-gcm check if the key is valid)
- change the name of the entry to $name-KEY2 and first try to load a property with the new name. If it exist, then it has been converted.

The second solution add a basic versioning of the storage format, which will be needed one day if a proper key rotation is implemented.
