### ISSUE TITLE
`Unwrapped` always return defaultValue after restart app

### ISSUE THREAD

**Issue by qchenqizhi** [alexruperez/SecurePropertyStorage#15]
**Describe the bug**
`Unwrapped` always return defaultValue after restart app

**To Reproduce**
```swift
    @UnwrappedCodableUserDefault(wrappedValue: "123", "key")
    var string: String
```
set the value for var string to "234", then restart app, it's value become to "123"

**Expected behavior**
defaultValue should only returned when never set the value.

**Environment**

**Additional context**

**Comment by qchenqizhi** [comment]
In addition, I think the test case needs to add some test persistence content, but I don’t know how to implement it, I’m not very familiar with testing.

**Comment by alexruperez** [comment]
Thanks for the fix @qchenqizhi!
Your changes and some pending unit tests added in #17 for 0.4.1 release. 👍
