### ISSUE TITLE
Clear keychain value ? 

### ISSUE THREAD

**Issue by X901** [alexruperez/SecurePropertyStorage#25]
Hi, 

How can I clear Keychain value ?
Like I want to remove all Data when user logout !

I didn't see any thing in your doc explain how to remove value or all values

**Comment by alexruperez** [comment]
Hi @X901, this library is just a property wrapper helper.
To remove a value from the keychain using this library, just set `nil` to your property.
To remove all values, you can try [this](https://stackoverflow.com/a/14086320).
